#ifndef TOKEN_LIST_H
#define TOKEN_LIST_H


enum tokens {EMPTY, IF, ELSE, WHILE, LET, PRINT, BINARYOP, UNARYOP, TERTIARYOP,
		EQUAL, NOT, COMPARE, PIPE, MULTIPLY, DIVIDE, BITWISEAND,
		AND, OR, PLUS, MINUS, POWER, GREATERTHAN, LESSTHAN,
		LESSEQUAL, GREATEREQUAL, NOTEQUAL, LEFTSHIFT,
		RIGHTSHIFT, INT, FLOAT, STRING, BOOL, NAME, LBRACKET,
		RBRACKET, LBRACE, RBRACE, LPAREN, RPAREN, SIN, COS,
		TAN, COMMENTS, ERROR};

#endif